### ISSUE TITLE
Walrus operator fails with 'Syntax Error'

### ISSUE THREAD

**Issue by karlicoss** [ymyzk/mypy-playground#64] opened 2019-10-26 11:41 UTC
I used 'latest mypy' and 'python3.8'. Walrus operator should be in mypy 0.730 according to the [changelog](https://mypy-lang.blogspot.com/2019/09/mypy-730-released.html). Example program:
```
if x := True:
    print(x)
```

**Comment by ymyzk** [comment] 2019-11-01 14:35
@karlicoss, thanks for reporting the issue. I could reproduce the issue.

It seems we need to run mypy itself on Python 3.8 to support syntax introduced in Python 3.8. Currently, we're using Python 3.7 to run mypy in the sandbox. I'll update the Docker image to fix this.

**Comment by ymyzk** [comment] 2019-11-01 14:54
The issue is fixed in #65. We can verify it using: https://mypy-play.net/?mypy=0.730&python=3.8&gist=29f50b32a55b993c911d15757817ae2e

**Closed** 2019-11-11 01:12 UTC
